In [8]:
# loading dependencies
import pandas as pd
import numpy as np
from sklearn import linear_model

# loading our data
medcost_df = pd.read_csv('insurance.csv')
# viewing few files
medcost_df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [16]:
sex = {'male': 0,'female': 1}
medcost_df.sex = [sex[item] for item in medcost_df.sex] 

In [17]:
smoker = {'no': 0,'yes': 1}
medcost_df.smoker = [smoker[item] for item in medcost_df.smoker] 

In [18]:
medcost_df.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [19]:
region = {'southwest': 0,'southeast': 1, 'northwest': 2,'northeast': 3}
medcost_df.region = [region[item] for item in medcost_df.region] 

In [21]:
# creating the model object
model = linear_model.LinearRegression() # y = mx+b

# defining X and y
features = ['age', 'sex', 'bmi', 'children', 'smoker', 'region']
X = medcost_df[features] # Features
y = medcost_df.charges # Target variable

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

# fitting model with X_train, y_train
model.fit(X_train,y_train)

LinearRegression()

In [26]:
# checking coeffiecent - m
model.coef_

array([  256.5772619 ,    49.39232379,   329.02381564,   479.08499828,
       23400.28378787,   276.31576201])

In [27]:
# checking intercept - b
model.intercept_

-12706.072751617743

In [34]:
# prediction
#prediction = model.predict(X_test)
X_new = np.array([23,1,25,0,0,1]).reshape(1,-1)
model.predict(X_new)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([1746.50774877])

In [35]:
# loading library
import pickle

# create an iterator object with write permission - model.pkl
with open('model_pkl', 'wb') as files:
    pickle.dump(model, files)

In [36]:
# load saved model
with open('model_pkl' , 'rb') as f:
    lr = pickle.load(f)

In [37]:
# check prediction
lr.predict([[23,1,25,0,0,1]]) # similar

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([1746.50774877])